package ihl.processing.chemistry;

import ihl.model.IHLModelRenderer;
import net.minecraft.client.model.ModelBase;
import net.minecraftforge.common.util.ForgeDirection;

// Date: 17.03.2015 21:30:34
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public class GaedesMercuryRotaryPumpModel extends ModelBase
{
  //fields
    IHLModelRenderer Base;
  
  public GaedesMercuryRotaryPumpModel()
  {
    textureWidth = 64;
    textureHeight = 32;
    setTextureOffset("Base.PipeN1", 0, 0);
    setTextureOffset("Base.PipeU3", 0, 0);
    setTextureOffset("Base.Shape3", 0, 0);
    setTextureOffset("Base.PipeN2", 0, 0);
    setTextureOffset("Base.Shape5", 0, 0);
    setTextureOffset("Base.Shape6", 0, 0);
    setTextureOffset("Base.Shape7", 0, 0);
    setTextureOffset("Base.PipeU4", 0, 0);
    setTextureOffset("Base.Shape1", 0, 0);
    setTextureOffset("Base.PipeW5", 0, 0);
    setTextureOffset("Base.Shape2", 0, 0);
    setTextureOffset("Base.Shape4", 0, 0);
    setTextureOffset("Base.Shape8", 0, 0);
    setTextureOffset("Base.PipeW8", 0, 0);
    
    Base = new IHLModelRenderer(this, "Base");
    Base.setRotationPoint(0F, 16F, 0F);
    setRotation(Base, 0F, 0F, 0F);
    Base.mirror = true;
      Base.addTube("PipeN1", -5F, -5F, -6F, 10, 10, 10,0F,1F,ForgeDirection.NORTH);
      Base.addTube("PipeU3", -0.5F, -2.5F, -8F, 1, 2, 1,0.1F,1F,ForgeDirection.UP);
      Base.addBox("Shape3", -0.5F, -0.5F, -8F, 1, 1, 2);
      Base.addTube("PipeN2", -3F, -2F, 4F, 6, 6, 4,0F,1F,ForgeDirection.NORTH);
      Base.addBox("Shape5", -7F, 7F, -6F, 14, 1, 14);
      Base.addBox("Shape6", 2F, 1F, -5F, 1, 6, 12);
      Base.addBox("Shape7", -3F, 1F, -5F, 1, 6, 12);
      Base.addTube("PipeU4", 0F, -8F, -5F, 1, 3, 1,0.1F,1F,ForgeDirection.UP);
      Base.addBox("Shape1", 0F, -7F, -5F, 1, 1, 1);
      Base.addTube("PipeW5", -1F, -7F, -5F, 8, 1, 1,0.1F,1F,ForgeDirection.WEST);
      Base.addBox("Shape2", 4F, -8F, -5F, 1, 2, 1);
      Base.addBox("Shape4", 4F, -8F, -1F, 1, 8, 1);
      Base.addBox("Shape8", -5F, -8F, -1F, 1, 8, 1);
      Base.addTube("PipeW8", -4F, -8F, -1F, 8, 1, 1,0.1F,1F,ForgeDirection.WEST);
  }
  
  private void setRotation(IHLModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
