// Date: 05.04.2015 16:30:47
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package ihl.processing.chemistry;

import ihl.model.IHLModelRenderer;
import net.minecraft.client.model.ModelBase;
import net.minecraftforge.common.util.ForgeDirection;


public class RefluxCondenserModel extends ModelBase
{
  //fields
    IHLModelRenderer Base;
    IHLModelRenderer RotatingPartZ;
  
  public RefluxCondenserModel()
  {
    textureWidth = 64;
    textureHeight = 32;
    setTextureOffset("Base.PipeUp03", 0, 0);
    setTextureOffset("Base.KneeUpEast", 0, 0);
    setTextureOffset("Base.WestPipe03", 0, 0);
    setTextureOffset("Base.WestPipe04", 0, 0);
    setTextureOffset("Base.WestPipe02", 0, 0);
    setTextureOffset("Base.WestPipe01", 0, 0);
    setTextureOffset("Base.Shape1", 0, 0);
    setTextureOffset("Base.PipeUp06", 0, 0);
    setTextureOffset("Base.PipeUp07", 0, 0);
    setTextureOffset("Base.PipeNorth07", 0, 0);
    setTextureOffset("Base.PipeNorth08", 0, 0);
    setTextureOffset("RotatingPartZ.ConeWest05", 0, 0);
    setTextureOffset("RotatingPartZ.PipeWest07", 0, 0);
    setTextureOffset("RotatingPartZ.ConeEast06", 0, 0);
    
    Base = new IHLModelRenderer(this, "Base");
    Base.setRotationPoint(0F, 16F, 0F);
    setRotation(Base, 0F, 0F, 0F);
    Base.mirror = true;
      Base.addTube("PipeUp03", -2F, 7F, -2F, 4, 1, 4, 0.6f, 1f,ForgeDirection.UP);
      Base.addKnee("KneeUpEast", -8F, 2F, -3F, 5, 6, 6, .8F, 1F, ForgeDirection.UP, ForgeDirection.EAST);
      Base.addTube("WestPipe03", 3.5F, -7F, -1.5F, 4, 3, 3, 0.8f, 1f,ForgeDirection.WEST);
      Base.addTube("WestPipe04", 7F, -7.5F, -2F, 1, 4, 4, 0.6f, 1f,ForgeDirection.WEST);
      Base.addTube("WestPipe02", 7F, 3F, -2F, 1, 4, 4, 0.6f, 1f,ForgeDirection.WEST);
      Base.addTube("WestPipe01", -3F, 3.5F, -1.5F, 10, 3, 3, .8F, 1F, ForgeDirection.WEST);
      Base.addTube("Shape1", -2F, -8F, -2F, 4, 1, 4, 0.6f, 1f,ForgeDirection.UP);
      Base.addTube("PipeUp06", -1.5F, -7F, -1.5F, 3, 2, 3, 0.8f, 1f,ForgeDirection.UP);
      Base.addTube("PipeUp07", -1.5F, 5F, -1.5F, 3, 2, 3, 0.8f, 1f,ForgeDirection.UP);
      Base.addTube("PipeNorth07", -2F, -2F, -8F, 4, 4, 1, 0.6f, 1f,ForgeDirection.NORTH);
      Base.addTube("PipeNorth08", -1.5F, -1.5F, -7F, 3, 3, 7, 0.8f, 1f,ForgeDirection.NORTH);
    RotatingPartZ = new IHLModelRenderer(this, "RotatingPartZ");
    RotatingPartZ.setRotationPoint(3F, 13F, 0F);
    setRotation(RotatingPartZ, 0F, 0F, -0.5F);
    RotatingPartZ.mirror = true;
      RotatingPartZ.addTube("ConeWest05", 1F, -4F, -4F, 2, 8, 8, 0f, 0.8f,ForgeDirection.WEST);
      RotatingPartZ.addTube("PipeWest07", -9F, -4F, -4F, 10, 8, 8, 0.8f, 1f,ForgeDirection.WEST);
      RotatingPartZ.addTube("ConeEast06", -11F, -4F, -4F, 2, 8, 8, 0f, 0.8f,ForgeDirection.EAST);
  }
  
  private void setRotation(IHLModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }


}
