package ihl.processing.metallurgy;

import ihl.model.IHLModelRenderer;
import net.minecraft.client.model.ModelBase;
import net.minecraftforge.common.util.ForgeDirection;

// Date: 23.02.2015 12:31:33
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public class GasWeldingStationModel extends ModelBase
{
  //fields
    IHLModelRenderer Base;
  
  public GasWeldingStationModel()
  {
    textureWidth = 64;
    textureHeight = 32;
    setTextureOffset("Base.Shape6", 0, 13);
    setTextureOffset("Base.Shape3", 0, 13);
    setTextureOffset("Base.Shape16", 0, 13);
    setTextureOffset("Base.Shape161", 0, 13);
    setTextureOffset("Base.Shape162", 0, 13);
    setTextureOffset("Base.Shape163", 0, 22);
    setTextureOffset("Base.Shape164", 0, 13);
    setTextureOffset("Base.Shape14", 0, 13);
    setTextureOffset("Base.Shape165", 0, 13);
    setTextureOffset("Base.Shape2", 0, 13);
    setTextureOffset("Base.Shape4", 15, 17);
    setTextureOffset("Base.Shape5", 12, 17);
    setTextureOffset("Base.Cone176DOWN", 0, 0);
    setTextureOffset("Base.Shape7", 0, 0);
    setTextureOffset("Base.Cone173DOWN", 24, 0);
    setTextureOffset("Base.Shape9", 24, 0);
    setTextureOffset("Base.Cone172UP", 24, 0);
    setTextureOffset("Base.Tube166UP", 48, 0);
    setTextureOffset("Base.Tube168Up", 48, 0);
    setTextureOffset("Base.Cone175UP", 0, 0);
    setTextureOffset("Base.Tube169UP", 48, 4);
    setTextureOffset("Base.Tube167UP", 50, 5);
    setTextureOffset("Base.Tube170UP", 57, 2);
    setTextureOffset("Base.Tube165UP", 48, 0);
    setTextureOffset("Base.Shape20", 48, 0);
    setTextureOffset("Base.Shape21", 48, 0);
    setTextureOffset("Base.Shape22", 28, 0);
    setTextureOffset("Base.Shape23", 28, 0);
    setTextureOffset("Base.Shape24", 26, 0);
    setTextureOffset("Base.Shape25", 26, 0);
    setTextureOffset("Base.Shape26", 26, 0);
    setTextureOffset("Base.Shape27", 0, 0);
    setTextureOffset("Base.Shape28", 0, 0);
    setTextureOffset("Base.Shape29", 0, 0);
    setTextureOffset("Base.Shape30", 0, 0);
    setTextureOffset("Base.Cone171WEST", 48, 0);
    
    Base = new IHLModelRenderer(this, "Base");
    Base.setRotationPoint(0F, 16F, 0F);
    setRotation(Base, 0F, 0F, 0F);
    Base.mirror = true;
      Base.addBox("Shape6", -8F, 7F, 0F, 1, 1, 8);
      Base.addBox("Shape3", -7F, 7F, 0F, 14, 1, 1);
      Base.addBox("Shape16", 7F, 7F, 0F, 1, 1, 8);
      Base.addBox("Shape161", -8F, -1F, 0F, 1, 8, 1);
      Base.addBox("Shape162", -8F, -2F, 1F, 1, 1, 6);
      Base.addBox("Shape163", -8F, -2F, -0F, 16, 1, 1);
      Base.addBox("Shape164", 7F, -1F, 0F, 1, 8, 1);
      Base.addBox("Shape14", 7F, -2F, 1F, 1, 1, 6);
      Base.addBox("Shape165", -8F, -2F, 7F, 16, 1, 1);
      Base.addBox("Shape2", -7F, 7F, 7F, 14, 1, 1);
      Base.addBox("Shape4", -8F, -1F, 7F, 1, 8, 1);
      Base.addBox("Shape5", 7F, -1F, 7F, 1, 8, 1);
      Base.addTube("Cone176DOWN", -7F, 5F, 1F, 6, 3, 6, 0.5F, 0.5F, ForgeDirection.UP);
      Base.addTube("Shape7", -7F, -2F, 1F, 6, 7, 6, 0F, 1F, ForgeDirection.UP);
      Base.addTube("Cone173DOWN", 1F, 5F, 1F, 6, 3, 6, 0.5F, 0.5F, ForgeDirection.UP);
      Base.addTube("Shape9", 1F, -2F, 1F, 6, 7, 6, 0F, 1F, ForgeDirection.UP);
      Base.addTube("Cone172UP", 1F, -5F, 1F, 6, 3, 6, 0.5F, 0.5F, ForgeDirection.DOWN);
      Base.addTube("Tube166UP", 2.5F, -8F, 2.5F, 3, 1, 3, 0F, 1F, ForgeDirection.UP);
      Base.addTube("Tube168Up", 2.5F, -6F, 2.5F, 3, 1, 3, 0F, 1F, ForgeDirection.UP);
      Base.addTube("Cone175UP", -7F, -5F, 1F, 6, 3, 6, 0.5F, 0.5F, ForgeDirection.DOWN);
      Base.addTube("Tube169UP", 3.5F, -7F, 3.5F, 1, 1, 1, 0F, 1F, ForgeDirection.UP);
      Base.addTube("Tube167UP", -5.5F, -6F, 2.5F, 3, 1, 3, 0F, 1F, ForgeDirection.UP);
      Base.addTube("Tube170UP", -4.5F, -7F, 3.5F, 1, 1, 1, 0F, 1F, ForgeDirection.UP);
      Base.addTube("Tube165UP", -5.5F, -8F, 2.5F, 3, 1, 3, 0F, 1F, ForgeDirection.UP);
      Base.addBox("Shape20", 1F, 7F, -7F, 7, 1, 1);
      Base.addBox("Shape21", 0F, 7F, -7.5F, 1, 1, 2);
      Base.addBox("Shape22", 3.5F, -6F, -1.5F, 1, 1, 4);
      Base.addBox("Shape23", -3F, 7F, -6.5F, 3, 1, 1);
      Base.addBox("Shape25",-2.8F, 7F, -1.5F, 7, 1, 1);
      Base.addBox("Shape26",-3F, 6.9F, -6F, 1, 1, 5);
      Base.addBox("Shape29",-4.7F, -5F, -1.5F, 1, 12, 1);
      Base.addBox("Shape24", 3.4F, -5F, -1.5F, 1, 12, 1);
      Base.addBox("Shape27", -5F, 7F, -8F, 5, 1, 1);
      Base.addBox("Shape28", -4.5F, -6F, -1.5F, 1, 1, 4);
      Base.addBox("Shape30", -4.9F, 6.9F, -7.5F, 1, 1, 7);
      Base.addTube("Cone171WEST", 7F, 7F, -6F, 1, 1, 2, 0.5F, 0.5F, ForgeDirection.NORTH);
  }
  
  private void setRotation(IHLModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
}
