// Date: 15.02.2015 11:28:39
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ihl.processing.metallurgy;

import ihl.model.IHLModelRenderer;
import net.minecraft.client.model.ModelBase;
import net.minecraftforge.common.util.ForgeDirection;

public class WoodenRollingMachinePart1Model extends ModelBase
{
  //fields
	IHLModelRenderer Base;
	IHLModelRenderer RotatingPart2;
	IHLModelRenderer MotorPart1;
	IHLModelRenderer MotorPart2;
	IHLModelRenderer RotatingPart1;
	IHLModelRenderer RotatingPart3;
	IHLModelRenderer RotatingPart4;
	IHLModelRenderer Belt1;
	IHLModelRenderer Belt2;
  
  public WoodenRollingMachinePart1Model()
  {
    textureWidth = 64;
    textureHeight = 32;
    setTextureOffset("Base.Shape6", 0, 15);
    setTextureOffset("Base.Shape16", 0, 23);
    setTextureOffset("Base.PipeN18", 0, 0);
    setTextureOffset("Base.PipeN19", 0, 0);
    setTextureOffset("RotatingPart2.PipeN17", 0, 0);
    setTextureOffset("RotatingPart2.PipeN21", 0, 0);
    setTextureOffset("RotatingPart2.PipeN25", 0, 0);
    setTextureOffset("MotorPart1.PipeN41", 0, 0);
    setTextureOffset("MotorPart1.PipeN13", 0, 0);
    setTextureOffset("MotorPart1.PipeN12", 0, 0);
    setTextureOffset("MotorPart1.PipeN16", 0, 0);
    setTextureOffset("MotorPart2.Shape4", 0, 24);
    setTextureOffset("MotorPart2.Shape7", 0, 9);
    setTextureOffset("MotorPart2.Shape10", 0, 9);
    setTextureOffset("RotatingPart1.PipeN27", 0, 0);
    setTextureOffset("RotatingPart1.PipN119", 0, 0);
    setTextureOffset("RotatingPart1.pipeN24", 0, 0);
    setTextureOffset("RotatingPart3.PipeN23", 0, 0);
    setTextureOffset("RotatingPart3.PipeN22", 0, 0);
    setTextureOffset("RotatingPart3.PipeN26", 0, 0);
    setTextureOffset("RotatingPart4.PipeN28", 0, 0);
    setTextureOffset("Belt1.Shape12", 60, 0);
    setTextureOffset("Belt2.Shape17", 60, 0);
    
    Base = new IHLModelRenderer(this, "Base");
    Base.setRotationPoint(0F, 16F, 0F);
    setRotation(Base, 0F, 0F, 0F);
    Base.mirror = true;
      Base.addBox("Shape6", -8F, 7F, -8F, 16, 1, 16);
      Base.addBox("Shape16", -6F, -1F, -7F, 12, 8, 1);
      Base.addTube("PipeN18", -5F, -6.1F, -7.1F, 10, 10, 1, 0.9F,1F,ForgeDirection.NORTH);
      Base.addTube("PipeN19", -1.5F, -6F, -7F, 3, 3, 1, 0.25F,1F,ForgeDirection.NORTH);;
    RotatingPart2 = new IHLModelRenderer(this, "RotatingPart2");
    RotatingPart2.setRotationPoint(-2.2F, 16F, -8F);
    setRotation(RotatingPart2, 0F, 0F, 0F);
    RotatingPart2.mirror = true;
      RotatingPart2.addTube("PipeN17", -2F, -2F, 2F, 4, 4, 28, 0F,1F,ForgeDirection.NORTH);
      RotatingPart2.addTube("PipeN21", -0.5F, -0.5F, 0F, 1, 1, 1, 0F,1F,ForgeDirection.NORTH);
      RotatingPart2.addTube("PipeN25", -0.5F, -0.5F, 30F, 1, 1, 2, 0F,1F,ForgeDirection.NORTH);
      MotorPart1 = new IHLModelRenderer(this, "MotorPart1");
      MotorPart1.setRotationPoint(4.5F, 20.5F, 0F);
      setRotation(MotorPart1, 0F, 0F, 0F);
      MotorPart1.mirror = true;
        MotorPart1.addTube("PipeN41", -1.5F, -1.5F, -8F, 3, 3, 1, 0F,1F,ForgeDirection.NORTH);
        MotorPart1.addTube("PipeN12", -0.5F, -0.5F, -7F, 1, 1, 1, 0F,1F,ForgeDirection.NORTH);
        MotorPart1.addTube("PipeN13", -1.5F, -1.5F, -5F, 3, 3, 5, 0F,1F,ForgeDirection.NORTH);
    MotorPart2 = new IHLModelRenderer(this, "MotorPart2");
    MotorPart2.setRotationPoint(0F, 16F, 0F);
    setRotation(MotorPart2, 0F, 0F, 0F);
    MotorPart2.mirror = true;
      MotorPart2.addBox("Shape4", 3F, 3F, 0F, 3, 4, 4);
      MotorPart2.addBox("Shape7", 6F, 3F, -5F, 2, 4, 5);
      MotorPart2.addBox("Shape10", 1F, 3F, -5F, 2, 4, 5);
    RotatingPart1 = new IHLModelRenderer(this, "RotatingPart1");
    RotatingPart1.setRotationPoint(0F, 11.5F, -6F);
    setRotation(RotatingPart1, 0F, 0F, 0F);
    RotatingPart1.mirror = true;
      RotatingPart1.addTube("PipeN27", -2F, -2F, 0F, 4, 4, 28, 0F,1F,ForgeDirection.NORTH);
      RotatingPart1.addTube("PipN119", -0.5F, -0.5F, -2F, 1, 1, 2, 0F,1F,ForgeDirection.NORTH);
      RotatingPart1.addTube("pipeN24", -0.5F, -0.5F, 28F, 1, 1, 2, 0F,1F,ForgeDirection.NORTH);
    RotatingPart3 = new IHLModelRenderer(this, "RotatingPart3");
    RotatingPart3.setRotationPoint(2.2F, 16F, -8F);
    setRotation(RotatingPart3, 0F, 0F, 0F);
    RotatingPart3.mirror = true;
      RotatingPart3.addTube("PipeN23", -2F, -2F, 2F, 4, 4, 28, 0F,1F,ForgeDirection.NORTH);
      RotatingPart3.addTube("PipeN22", -1.5F, -1.5F, 0F, 3, 3, 1, 0F,1F,ForgeDirection.NORTH);
      RotatingPart3.addTube("PipeN26", -0.5F, -0.5F, 30F, 1, 1, 2, 0F,1F,ForgeDirection.NORTH);
    RotatingPart4 = new IHLModelRenderer(this, "RotatingPart4");
      RotatingPart4.setRotationPoint(0F, 15F, -5F);
      setRotation(RotatingPart3, 0F, 0F, 0F);
      RotatingPart4.mirror = true;
        RotatingPart4.addTube("PipeN28", -0.5F, -0.5F, 0F, 1, 1, 27, 0F,1F,ForgeDirection.NORTH);
    Belt1 = new IHLModelRenderer(this, "Belt1");
    Belt1.setRotationPoint(2.5F, 16F, -7.9F);
    setRotation(Belt1, 0F, 0F, -0.45F);
    Belt1.mirror = true;
      Belt1.addBox("Shape12", 0F, 0F, 0F, 1, 5, 1);
    Belt2 = new IHLModelRenderer(this, "Belt2");
    Belt2.setRotationPoint(2F, 16F, -7.9F);
    setRotation(Belt2, 0F, 0F, -0.45F);
    Belt2.mirror = true;
      Belt2.addBox("Shape17", -1F, 0F, 0F, 1, 6, 1);
  }
  
 
  private void setRotation(IHLModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
