// Date: 15.02.2015 11:31:12
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ihl.processing.metallurgy;

import net.minecraft.client.model.ModelBase;
import net.minecraftforge.common.util.ForgeDirection;
import ihl.model.IHLModelRenderer;

public class WoodenRollingMachinePart2Model extends ModelBase
{
  //fields
    IHLModelRenderer Base;
  
  public WoodenRollingMachinePart2Model()
  {
    textureWidth = 64;
    textureHeight = 32;
    setTextureOffset("Base.Shape6", 0, 15);
    setTextureOffset("Base.Shape16", 0, 23);
    setTextureOffset("Base.PipeN18", 0, 0);
    setTextureOffset("Base.PipeN19", 0, 0);
    
    Base = new IHLModelRenderer(this, "Base");
    Base.setRotationPoint(0F, 16F, 0F);
    setRotation(Base, 0F, 0F, 0F);
    Base.mirror = true;
      Base.addBox("Shape6", -8F, 7F, -8F, 16, 1, 16);
      Base.addBox("Shape16", -6F, -1F, 6F, 12, 8, 1);
      Base.addTube("PipeN18", -5F, -6.1F, 6.1F, 10, 10, 1, 0.9F,1F,ForgeDirection.NORTH);
      Base.addTube("PipeN19", -1.5F, -6F, 6F, 3, 3, 1, 0.25F,1F,ForgeDirection.NORTH);;
  }
  
  private void setRotation(IHLModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
