package ihl.flexible_cable;

import net.minecraft.client.model.ModelBase;
import net.minecraftforge.common.util.ForgeDirection;
import ihl.model.IHLModelRenderer;

// Date: 07.04.2015 18:24:15
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public class BatterySwitchUnitModel extends ModelBase
{
  //fields
    IHLModelRenderer Piece1;
  
  public BatterySwitchUnitModel()
  {
    textureWidth = 64;
    textureHeight = 32;
    setTextureOffset("Piece1.Shape1", 0, 0);
    setTextureOffset("Piece1.ConeUp01", 0, 0);
    setTextureOffset("Piece1.PipeUp", 54, 0);
    setTextureOffset("Piece1.ConeUp02", 0, 0);
    setTextureOffset("Piece1.Shape27", 0, 0);
    setTextureOffset("Piece1.ConeUp04", 0, 0);
    
    Piece1 = new IHLModelRenderer(this, "Piece1");
    Piece1.setRotationPoint(0F, 16F, 0F);
    setRotation(Piece1, 0F, 0F, 0F);
    Piece1.mirror = true;
      Piece1.addBox("Shape1", -8F, -8F, -8F, 16, 16, 16);
      Piece1.addTube("ConeUp01", -2F, -16F, -2F, 4, 2, 4, 0f, 0.5f, ForgeDirection.DOWN);
      Piece1.addTube("PipeUp", -0.5F, -17F, -0.5F, 1, 1, 1, 0f, 1f, ForgeDirection.DOWN);
      Piece1.addTube("ConeUp02", -2F, -14F, -2F, 4, 2, 4, 0f, 0.5f, ForgeDirection.DOWN);
      Piece1.addTube("Shape27", -2F, -12F, -2F, 4, 2, 4, 0f, 0.5f, ForgeDirection.DOWN);
      Piece1.addTube("ConeUp04", -2F, -10F, -2F, 4, 2, 4, 0f, 0.5f, ForgeDirection.DOWN);
    }
  
  private void setRotation(IHLModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
}
